apiVersion: batch/v1
kind: Job
metadata:
  name: {{ default .Release.Name .Values.name }}-cleanup-job-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PostDelete
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      containers:
      - name: cleanup
        image: {{ index .Values "apolo-hooks" "image" "repository" }}:{{ index .Values "apolo-hooks" "image" "tag" }}
        command: ["python3", "-m", "apolo_apps_postgresql.scripts.cleanup_secrets"]
        env:
        - name: APOLO_PASSED_CONFIG
          value: {{ .Values.APOLO_PASSED_CONFIG | quote }}
        - name: APP_ID
          value: {{ .Values.apolo_app_id | quote }}
